import {LabRenderer,responses} from './webgl.js?v=6';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const chapters=[
{key:'world',kicker:'PROLOGO',name:'Il mondo percepito',title:'Di che colore è il mondo?',text:'Prima osserva. Per qualche secondo non cercare una spiegazione: fidati della percezione.',label:'Punto di partenza',thesis:'Il mondo sembra arrivare a noi già colorato.',detail:'Questa prima scena è intenzionalmente priva di grafici. L’esperimento parte dal realismo percettivo spontaneo: la mela sembra rossa, l’erba verde, il cielo colorato. Solo dopo scomporremo ciò che sta accadendo.',stage:'SCENA 3D · PERCEZIONE'},
{key:'apple',kicker:'FASE 01',name:'La mela',title:'La mela è rossa?',text:'Ruota leggermente l’oggetto. Poi passa dalla risposta intuitiva alla descrizione fisica.',label:'Domanda',thesis:'Il rosso sembra una proprietà della mela. Ma che cosa troviamo davvero nella sua superficie?',detail:'Una superficie reale non riflette una sola lunghezza d’onda. Modifica una distribuzione spettrale complessa. La risposta percettiva dipende anche dall’illuminazione e dal sistema visivo.',stage:'SCENA 3D · SUPERFICIE E LUCE'},
{key:'light',kicker:'FASE 02',name:'La luce',title:'La luce non è colorata.',text:'Nel laboratorio 3D il fascio viene scomposto. Sposta il cursore lungo lo spettro visibile.',label:'Descrizione fisica',thesis:'La fisica misura lunghezza d’onda, frequenza ed energia. Nessuna di queste grandezze è una tinta.',detail:'Il colore associato al cursore è una traduzione per il nostro sistema visivo e per lo schermo RGB. La radiazione elettromagnetica, descritta fisicamente, non possiede “rosso” o “verde” come proprietà.',stage:'SCENA 3D · SPETTRO ELETTROMAGNETICO'},
{key:'rgb',kicker:'FASE 03',name:'Sintesi RGB',title:'Mescolare luci nello spazio.',text:'Tre proiettori tridimensionali convergono sulla stessa superficie. Regola le intensità.',label:'Attenzione',thesis:'Qui stiamo sommando luci, non mescolando pigmenti.',detail:'Gli schermi sfruttano la sintesi additiva: combinando tre canali si producono molte esperienze cromatiche. Questo non significa che il mondo sia composto da tre colori fondamentali.',stage:'SCENA 3D · SINTESI ADDITIVA'},
{key:'eye',kicker:'FASE 04',name:'Dentro l’occhio',title:'La retina non invia colori.',text:'Segui il fascio dentro un modello 3D semplificato dell’occhio e modifica lo stimolo.',label:'Trasduzione',thesis:'I coni S, M e L rispondono con intensità relative. Il cervello riceve segnali, non piccole macchie colorate.',detail:'Le curve di sensibilità dei coni sono ampie e sovrapposte. Chiamarli semplicemente “blu, verdi e rossi” è una semplificazione fuorviante.',stage:'SCENA 3D · OCCHIO E FOTORECETTORI'},
{key:'neural',kicker:'FASE 05',name:'Il cervello',title:'Dal segnale all’esperienza.',text:'Osserva il percorso semplificato retina → nervo ottico → talamo → corteccia. Poi ricostruisci la scena.',label:'Rivelazione',thesis:'Il colore nasce nell’elaborazione percettiva, non viaggia già pronto lungo il nervo ottico.',detail:'La visualizzazione è intenzionalmente schematica: non rappresenta ogni stadio neurale. Serve a mostrare il cambio di livello tra dati retinici, elaborazione e esperienza percettiva.',stage:'SCENA 3D · ELABORAZIONE NEURALE'},
{key:'context',kicker:'FASE 06',name:'Il contesto',title:'La stessa mela, quattro luci.',text:'Cambia illuminazione senza cambiare l’oggetto. Il segnale fisico varia più della nostra impressione di identità cromatica.',label:'Costanza cromatica',thesis:'Il sistema visivo interpreta lo stimolo in rapporto all’illuminazione e al contesto.',detail:'La costanza cromatica non è perfetta, ma mostra che la percezione non registra passivamente i valori ricevuti: stima relazioni e condizioni di illuminazione.',stage:'SCENA 3D · ILLUMINAZIONE'},
{key:'observer',kicker:'FASE 07',name:'Cambia osservatore',title:'Qual è il vero colore del fiore?',text:'La geometria 3D resta identica. Cambia soltanto il modello del sistema percettivo.',label:'Limite scientifico',thesis:'Queste sono traduzioni didattiche informate: non fotografie della coscienza di un’altra specie.',detail:'Conosciamo recettori, sensibilità e comportamenti di molte specie. Non possiamo però osservare direttamente la qualità soggettiva della loro esperienza.',stage:'SCENA 3D · SISTEMI VISIVI'},
{key:'final',kicker:'EPILOGO',name:'Scomposizione finale',title:'Disattiva progressivamente la costruzione percettiva.',text:'La stessa mela attraversa sei livelli: esperienza, saturazione, luminanza, retina, segnale nervoso, descrizione fisica.',label:'Conclusione',thesis:'Il colore è reale come esperienza, ma non è una proprietà assoluta dell’oggetto.',detail:'La percezione non è una fotografia passiva del mondo, ma neppure un’invenzione arbitraria: è una costruzione biologica vincolata dalla realtà fisica.',stage:'SCENA 3D · DALL’ESPERIENZA ALLA FISICA'}
];
let page=0,audio=false,renderer=null;
try{
  renderer=new LabRenderer($('#gl'));
  const gl=renderer.gl;
  window.__coloriWebGLProbe={available:true,version:gl.getParameter(gl.VERSION),renderer:gl.getParameter(gl.RENDERER)};
}catch(err){
  window.ColoriDiagnostics?.showRendererError(err);
}
const controls={
world:()=>`<div class="control-row"><span class="choice active">Scena percettiva</span><span class="choice">Stessa realtà, prima della scomposizione</span></div>`,
apple:()=>`<div class="control-row"><button class="action" id="analyze" type="button">${renderer?.state.analyze?'Torna alla percezione':'Analizza la luce'}</button><span class="choice">Trascina per cambiare leggermente il punto di vista</span></div>`,
light:()=>`<div class="range-wrap"><label for="wave">380 nm</label><input id="wave" type="range" min="380" max="700" value="${renderer?.state.wavelength||550}"><output id="waveOut">${renderer?.state.wavelength||550} nm</output></div><div class="readout"><div><span>Frequenza</span><strong id="freq"></strong></div><div><span>Energia</span><strong id="energy"></strong></div><div><span>Intervallo</span><strong>visibile umano</strong></div></div>`,
rgb:()=>{const v=renderer?.state.rgb||[255,150,55];return `<div class="triple">${['R','G','B'].map((c,i)=>`<label>${c}<input class="rgbRange" data-i="${i}" type="range" min="0" max="255" value="${v[i]}"><output>${v[i]}</output></label>`).join('')}</div>`},
eye:()=>`<div class="range-wrap"><label for="eyeWave">Stimolo</label><input id="eyeWave" type="range" min="380" max="700" value="${renderer?.state.eyeWave||560}"><output id="eyeOut">${renderer?.state.eyeWave||560} nm</output></div><div class="readout"><div><span>Coni S</span><strong id="sResp"></strong></div><div><span>Coni M</span><strong id="mResp"></strong></div><div><span>Coni L</span><strong id="lResp"></strong></div></div>`,
neural:()=>`<div class="control-row"><button class="action" id="build" type="button">${renderer?.state.built?'Scomponi di nuovo':'Costruisci l’esperienza'}</button><span class="choice">Gli impulsi continuano a muoversi lungo il percorso</span></div>`,
context:()=>`<div class="control-row">${[['day','Sole'],['sunset','Tramonto'],['cold','Luce fredda'],['shadow','Ombra']].map(([k,n])=>`<button class="choice ${renderer?.state.context===k?'active':''}" data-context="${k}" type="button">${n}</button>`).join('')}</div>`,
observer:()=>`<div class="control-row">${[['human','Essere umano'],['dog','Cane'],['bee','Ape'],['bird','Uccello']].map(([k,n])=>`<button class="choice ${renderer?.state.observer===k?'active':''}" data-observer="${k}" type="button">${n}</button>`).join('')}</div>`,
final:()=>`<div class="range-wrap"><label for="finalRange">Esperienza</label><input id="finalRange" type="range" min="0" max="5" step="1" value="${renderer?.state.final||0}"><output id="finalOut">${['Completa','Colore ridotto','Luminanza','Retina','Segnale','Fisica'][renderer?.state.final||0]}</output></div>`
};
function tone(f=440){if(!audio||!window.AudioContext)return;const C=tone.c||(tone.c=new AudioContext),o=C.createOscillator(),g=C.createGain();o.frequency.value=f;g.gain.setValueAtTime(.024,C.currentTime);g.gain.exponentialRampToValueAtTime(.0001,C.currentTime+.06);o.connect(g).connect(C.destination);o.start();o.stop(C.currentTime+.07)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200)}
function hud(){const c=chapters[page],s=renderer?.state||{},right={world:'Luce · superficie · osservatore',apple:s.analyze?'riflettanza · assorbimento':'esperienza cromatica',light:`λ ${s.wavelength||550} nm`,rgb:`RGB ${s.rgb?.join(' · ')||'255 · 150 · 55'}`,eye:`S/M/L · ${s.eyeWave||560} nm`,neural:s.built?'esperienza ricostruita':'segnali neurali',context:s.context||'day',observer:s.observer||'human',final:`livello ${(s.final||0)+1}/6`}[c.key];$('#hud').innerHTML=`<span class="tag">${c.stage}</span><span class="data"><b>${right}</b><span>modello didattico interattivo</span></span>`}
function metricsLight(){const w=+$('#wave')?.value;if(!w)return;$('#waveOut').value=`${w} nm`;$('#freq').textContent=`${Math.round(299792.458/w)} THz`;$('#energy').textContent=`${(1239.842/w).toFixed(2)} eV`}
function metricsEye(){const w=+$('#eyeWave')?.value;if(!w)return;const r=responses(w);$('#eyeOut').value=`${w} nm`;$('#sResp').textContent=`${Math.round(r.s*100)}%`;$('#mResp').textContent=`${Math.round(r.m*100)}%`;$('#lResp').textContent=`${Math.round(r.l*100)}%`}
function bindControls(){if(!renderer)return;const key=chapters[page].key;if(key==='apple')$('#analyze').onclick=()=>{renderer.state.analyze=!renderer.state.analyze;renderControls();hud();tone(renderer.state.analyze?260:560)};if(key==='light'){metricsLight();$('#wave').oninput=e=>{renderer.state.wavelength=+e.target.value;metricsLight();hud()}}if(key==='rgb')$$('.rgbRange').forEach(el=>el.oninput=e=>{const i=+e.target.dataset.i;renderer.state.rgb[i]=+e.target.value;e.target.nextElementSibling.value=e.target.value;hud()});if(key==='eye'){metricsEye();$('#eyeWave').oninput=e=>{renderer.state.eyeWave=+e.target.value;metricsEye();hud()}}if(key==='neural')$('#build').onclick=()=>{renderer.state.built=!renderer.state.built;renderControls();hud();tone(renderer.state.built?680:240)};if(key==='context')$$('[data-context]').forEach(b=>b.onclick=()=>{renderer.state.context=b.dataset.context;renderControls();hud();tone(360+$$('[data-context]').indexOf(b)*70)});if(key==='observer')$$('[data-observer]').forEach(b=>b.onclick=()=>{renderer.state.observer=b.dataset.observer;renderControls();hud();tone(400+$$('[data-observer]').indexOf(b)*80)});if(key==='final')$('#finalRange').oninput=e=>{renderer.state.final=+e.target.value;$('#finalOut').value=['Completa','Colore ridotto','Luminanza','Retina','Segnale','Fisica'][renderer.state.final];hud();tone(620-renderer.state.final*65)}}
function renderControls(){const key=chapters[page].key;$('#controls').innerHTML=controls[key]();bindControls()}
function chrome(){const c=chapters[page];$('#chapterKicker').textContent=c.kicker;$('#chapterName').textContent=c.name;$('#eyebrow').textContent=`Esperienza ${String(page+1).padStart(2,'0')}`;$('#screenTitle').textContent=c.title;$('#screenText').textContent=c.text;$('#thesisLabel').textContent=c.label;$('#thesisText').textContent=c.thesis;$('#details').textContent=c.detail;$('#stageLabel').textContent=c.stage;$('#progressFill').style.width=`${(page+1)/chapters.length*100}%`;$('#progressCount').textContent=`${page+1} / ${chapters.length}`;$('#prev').disabled=page===0;$('#next').disabled=page===chapters.length-1;$('#prevName').textContent=page?chapters[page-1].name:'—';$('#nextName').textContent=page<chapters.length-1?chapters[page+1].name:'Fine';$$('#dots button').forEach((b,i)=>b.classList.toggle('active',i===page));renderer?.setMode(c.key);renderControls();hud();$('#details').hidden=true;$('#detailToggle').setAttribute('aria-expanded','false')}
function go(n){if(n<0||n>=chapters.length||n===page)return;page=n;chrome();tone(360+n*34)}
chapters.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.ariaLabel=`Vai a ${c.name}`;b.onclick=()=>go(i);$('#dots').append(b)});
$('#prev').onclick=()=>go(page-1);$('#next').onclick=()=>go(page+1);$('#home').onclick=e=>{e.preventDefault();go(0)};document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')go(page+1);if(e.key==='ArrowLeft')go(page-1)});$('#detailToggle').onclick=e=>{const open=$('#details').hidden;$('#details').hidden=!open;e.currentTarget.setAttribute('aria-expanded',open)};$('#contrast').onclick=e=>e.currentTarget.setAttribute('aria-pressed',document.body.classList.toggle('contrast'));$('#motion').onclick=e=>{const v=document.body.classList.toggle('static');e.currentTarget.setAttribute('aria-pressed',v);renderer?.setReduced(v);toast(v?'Movimenti continui ridotti':'Movimenti riattivati')};$('#audio').onclick=e=>{audio=!audio;e.currentTarget.setAttribute('aria-pressed',audio);if(audio)tone(620)};if(matchMedia('(prefers-reduced-motion: reduce)').matches){document.body.classList.add('static');renderer?.setReduced(true);$('#motion').setAttribute('aria-pressed','true')}const noServiceWorker=new URLSearchParams(location.search).has('no-sw');if(!noServiceWorker&&'serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=6').catch(console.warn));chrome();
if(!noServiceWorker&&'serviceWorker'in navigator&&location.protocol.startsWith('http')&&document.readyState==='complete')navigator.serviceWorker.register('./sw.js?v=6').catch(console.warn);
